name: Validate content packs

on:
  pull_request:
    branches: ['**']
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout validator tools
        uses: actions/checkout@v4
        with:
          repository: Aharoni-Lab/labki-packs-tools
          path: tools-cache

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Labki validator
        run: |
          pip install ./tools-cache
          # Copy schema files into installed package for runtime discovery
          site=$(python -c "import site; print(site.getsitepackages()[0])")
          mkdir -p "$site/labki_packs_tools/schema"
          cp -r tools-cache/schema/* "$site/labki_packs_tools/schema/"

      - name: Validate manifest
        run: |
          # schema_version field inside manifest.yml determines which schema is used
          export LABKI_SCHEMA_DIR=$GITHUB_WORKSPACE/tools-cache/schema
          labki-validate validate manifest.yml --json
