name: Validate content packs
on:
  pull_request:
    branches: ['**']
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Aharoni-Lab/labki-packs-tools
          path: tools-cache
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install ./tools-cache
      - name: Validate manifest (auto schema)
        run: |
          # Auto schema selection based on manifest.schema_version
          python -m labki_packs_tools.validate_repo validate manifest.yml